name = "DeepSeek V3.2"
family = "deepseek"
release_date = "2025-11-20"
last_updated = "2025-11-20"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-09"
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.56
output = 1.68
cache_read = 0.28

[limit]
context = 163_840
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
