name = "Gemini 2.5 Flash"
family = "gemini"
release_date = "2025-04-17"
last_updated = "2025-06-05"
attachment = true
reasoning = true
temperature = true
knowledge = "2025-01"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.3
output = 2.50
cache_read = 0.03

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "audio", "video"]
output = ["text"]
