name = "Grok 4 Fast (Reasoning)"
family = "grok"
release_date = "2026-02-01"
last_updated = "2026-02-01"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.2
output = 0.5
cache_read = 0.05

[limit]
context = 2_000_000
output = 131_072

[modalities]
input = ["text", "image"]
output = ["text"]
