name = "Kimi K2.5"
family = "kimi"
release_date = "2026-02-15"
last_updated = "2026-02-15"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.5
output = 2.80

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text", "image", "video"]
output = ["text"]
