name = "Kimi K2 Thinking"
family = "kimi"
release_date = "2026-01-20"
last_updated = "2026-01-20"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.6
output = 2.50
cache_read = 0.15

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
