name = "MiniMax M2"
family = "minimax"
release_date = "2026-02-10"
last_updated = "2026-02-10"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.3
output = 1.20
cache_write = 0.375

[limit]
context = 204_800
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
