name = "o4-mini"
family = "o-mini"
release_date = "2025-04-16"
last_updated = "2025-04-16"
attachment = true
reasoning = true
temperature = false
knowledge = "2024-05"
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 1.10
output = 4.40
cache_read = 0.275

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
