name = "Qwen 3.6 Plus"
family = "qwen"
release_date = "2026-04-02"
last_updated = "2026-04-02"
attachment = true
reasoning = true
temperature = true
tool_call = true
open_weights = false

[cost]
input = 0.5
output = 3.00
cache_read = 0.1

[limit]
context = 1_000_000
output = 65_536

[modalities]
input = ["text", "image", "video"]
output = ["text"]
