name = "Qwen 3 Coder 480B A35B Instruct FP8"
family = "qwen"
release_date = "2026-02-20"
last_updated = "2026-02-20"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 2.00
output = 2.00

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
